MATERIAS
INSERT INTO materias (nombre, horas) VALUES ('Matematicas I', '5');
    INSERT INTO materias (nombre, horas) VALUES('Matematicas II', '5');
    INSERT INTO materias (nombre, horas) VALUES('Física I', '4');
    INSERT INTO materias (nombre, horas) VALUES('Física II', '4');
    INSERT INTO materias (nombre, horas) VALUES('Química General', '3');
    INSERT INTO materias (nombre, horas) VALUES('Introducción a la Ingeniería', '2');
    INSERT INTO materias (nombre, horas) VALUES('Programación y Algoritmos', '4');
    INSERT INTO materias (nombre, horas) VALUES('Circuitos Eléctricos I', '5');
    INSERT INTO materias (nombre, horas) VALUES('Circuitos Eléctricos II', '5');
    INSERT INTO materias (nombre, horas) VALUES('Cálculo Vectorial', '4');
    INSERT INTO materias (nombre, horas) VALUES('Ecuaciones Diferenciales', '4');
    INSERT INTO materias (nombre, horas) VALUES('Mecánica Clásica', '4');
    INSERT INTO materias (nombre, horas) VALUES('Termodinámica', '4');
    INSERT INTO materias (nombre, horas) VALUES('Electrónica Analógica', '5');
    INSERT INTO materias (nombre, horas) VALUES('Electrónica Digital', '5');
    INSERT INTO materias (nombre, horas) VALUES('Probabilidad y Estadística', '3');
    INSERT INTO materias (nombre, horas) VALUES('Mecánica de Fluidos', '4');
    INSERT INTO materias (nombre, horas) VALUES('Materiales de Ingeniería', '3');
    INSERT INTO materias (nombre, horas) VALUES('Sistemas de Control', '4');
    INSERT INTO materias (nombre, horas) VALUES('Ingeniería Económica', '3');
    INSERT INTO materias (nombre, horas) VALUES('Procesos de Manufactura', '4');
    INSERT INTO materias (nombre, horas) VALUES('Diseño Asistido por Computadora (CAD)', '3');
    INSERT INTO materias (nombre, horas) VALUES('Termodinámica Aplicada', '4');
    INSERT INTO materias (nombre, horas) VALUES('Análisis Numérico', '3');
    INSERT INTO materias (nombre, horas) VALUES('Ingeniería Ambiental', '3');
    INSERT INTO materias (nombre, horas) VALUES('Electromagnetismo', '4');
    INSERT INTO materias (nombre, horas) VALUES ('Ingeniería de Proyectos', '3');
    INSERT INTO materias (nombre, horas) VALUES('Ingeniería de Software', '4');
    INSERT INTO materias (nombre, horas) VALUES('Redes de Computadoras', '4');
    INSERT INTO materias (nombre, horas) VALUES('Sistemas Operativos', '3');
    INSERT INTO materias (nombre, horas) VALUES('Teoría de Circuitos', '4');
    INSERT INTO materias (nombre, horas) VALUES('Robótica y Automatización', '4');
    INSERT INTO materias (nombre, horas) VALUES('Investigación de Operaciones', '3');
    INSERT INTO materias (nombre, horas) VALUES('Ingeniería de Control de Calidad', '4');
    INSERT INTO materias (nombre, horas) VALUES('Tecnologías de la Información', '3');
    INSERT INTO materias (nombre, horas) VALUES('Comunicaciones Digitales', '4');
    INSERT INTO materias (nombre, horas) VALUES('Energías Renovables', '4');
    INSERT INTO materias (nombre, horas) VALUES('Ingeniería de Sistemas', '4');
    INSERT INTO materias (nombre, horas) VALUES('Seguridad y Salud Ocupacional', '3');
    INSERT INTO materias (nombre, horas) VALUES('Ética y Responsabilidad Profesional', '3');
    INSERT INTO materias(nombre, horas) VALUES
    INSERT INTO materias(nombre, horas) VALUES ('Anatomía Humana', '6'),
        INSERT INTO materias(nombre, horas) VALUES('Histología y Embriología', '4'),
       INSERT INTO materias(nombre, horas) VALUES ('Biología Celular', '4'),
        INSERT INTO materias(nombre, horas) VALUES('Bioquímica', '5'),
        INSERT INTO materias(nombre, horas) VALUES('Fisiología', '6'),
        INSERT INTO materias(nombre, horas) VALUES('Farmacología', '5'),
        INSERT INTO materias(nombre, horas) VALUES('Inmunología', '4'),
       INSERT INTO materias(nombre, horas) VALUES ('Genética Médica', '4'),
       INSERT INTO materias(nombre, horas) VALUES ('Patología', '6'),
       INSERT INTO materias(nombre, horas) VALUES ('Microbiología y Parasitología', '5'),
      INSERT INTO materias(nombre, horas) VALUES  ('Epidemiología', '4'),
       INSERT INTO materias(nombre, horas) VALUES ('Semiología Médica', '5'),
        INSERT INTO materias(nombre, horas) VALUES('Farmacología Clínica', '5'),
        INSERT INTO materias(nombre, horas) VALUES('Medicina Preventiva', '4'),
     INSERT INTO materias(nombre, horas) VALUES   ('Neurociencias', '6'),
      INSERT INTO materias(nombre, horas) VALUES  ('Salud Pública', '4'),
      INSERT INTO materias(nombre, horas) VALUES  ('Medicina Interna I', '7'),
       INSERT INTO materias(nombre, horas) VALUES ('Medicina Interna II', '7'),
       INSERT INTO materias(nombre, horas) VALUES ('Pediatría', '6'),
     INSERT INTO materias(nombre, horas) VALUES   ('Ginecología y Obstetricia', '6'),
       INSERT INTO materias(nombre, horas) VALUES ('Cirugía General I', '7'),
        INSERT INTO materias(nombre, horas) VALUES('Cirugía General II', '7'),
        INSERT INTO materias(nombre, horas) VALUES('Oftalmología', '5'),
        INSERT INTO materias(nombre, horas) VALUES('Otorrinolaringología', '5'),
        INSERT INTO materias(nombre, horas) VALUES('Radiología e Imagenología', '5'),
        INSERT INTO materias(nombre, horas) VALUES('Dermatología', '5'),
       INSERT INTO materias(nombre, horas) VALUES ('Psiquiatría', '6'),
       INSERT INTO materias(nombre, horas) VALUES ('Ortopedia y Traumatología', '6'),
     INSERT INTO materias(nombre, horas) VALUES   ('Medicina Legal', '5'),
       INSERT INTO materias(nombre, horas) VALUES ('Medicina Interna III', '8'),
        INSERT INTO materias(nombre, horas) VALUES('Medicina Intensiva', '6'),
        INSERT INTO materias(nombre, horas) VALUES('Oncología Médica', '6'),
        INSERT INTO materias(nombre, horas) VALUES('Cardiología', '6'),
        INSERT INTO materias(nombre, horas) VALUES('Nefrología', '6'),
       INSERT INTO materias(nombre, horas) VALUES ('Endocrinología', '5'),
      INSERT INTO materias(nombre, horas) VALUES  ('Neumología', '5'),
       INSERT INTO materias(nombre, horas) VALUES ('Hematología', '5'),
       INSERT INTO materias(nombre, horas) VALUES ('Reumatología', '5'),
       INSERT INTO materias(nombre, horas) VALUES ('Gastroenterología', '6');
       INSERT INTO Materias (nombre, horas) VALUES
    ('Anatomía Oral', '6'),
    ('Histología Dental', '4'),
    ('Embriología Craneofacial', '4'),
    ('Bioquímica Dental', '5'),
    ('Fisiología Oral', '6'),
    ('Farmacología Dental', '5'),
    ('Radiología Dental', '4'),
    ('Patología Oral', '6'),
    ('Periodoncia', '7'),
    ('Endodoncia', '7'),
    ('Operatoria Dental', '6'),
    ('Odontopediatría', '6'),
    ('Cirugía Oral I', '7'),
    ('Cirugía Oral II', '7'),
    ('Ortodoncia', '6'),
    ('Prótesis Dental I', '6'),
    ('Prótesis Dental II', '6'),
    ('Odontología Restauradora', '5'),
    ('Implantología Dental', '6'),
    ('Odontología Estética', '5'),
    ('Ortopedia Maxilar', '5'),
    ('Odontología Preventiva', '4'),
    ('Salud Pública Dental', '4'),
    ('Radiología Maxilofacial', '5'),
    ('Oral Patología', '6'),
    ('Anestesiología Dental', '4'),
    ('Odontología Geriátrica', '5'),
    ('Oral y Maxilofacial Cirugía', '8'),
    ('Oral Medicina', '6'),
    ('Farmacología Clínica Dental', '5'),
    ('Dentística', '5'),
    ('Odontología Comunitaria', '4'),
    ('Oral y Maxilofacial Diagnóstico', '6'),
    ('Odontología Legal', '5'),
    ('Periodoncia Quirúrgica', '6'),
    ('Radiología Oral', '5'),
    ('Oral y Maxilofacial Traumatología', '6'),
    ('Odontología Integrada', '7'),
    ('Estomatología', '7'),
    ('Prótesis Dental Removible', '6'),
	('Introduccion a la Administración', '6'),
    ('Matematicas para la Administración', '4'),
    ('Estadística Aplicada', '4'),
    ('Contabilidad I', '5'),
    ('Contabilidad II', '6'),
    ('Economía General', '5'),
    ('Microeconomía', '4'),
    ('Macroeconomía', '4'),
    ('Finanzas Corporativas', '6'),
    ('Gestión de Recursos Humanos', '6'),
    ('Comportamiento Organizacional', '5'),
    ('Mercadotecnia', '6'),
    ('Investigación de Mercados', '5'),
    ('Planificación Estratégica', '6'),
    ('Gestión de Operaciones', '5'),
    ('Logística y Cadena de Suministro', '5'),
    ('Administración de Proyectos', '5'),
    ('Comunicación Organizacional', '4'),
    ('Ética Empresarial', '4'),
    ('Derecho Empresarial', '6'),
    ('Gestión de la Calidad', '5'),
    ('Gestión de la Innovación', '5'),
    ('Emprendimiento', '4'),
    ('Negociación y Resolución de Conflictos', '5'),
    ('Liderazgo y Motivación', '4'),
    ('Gestión de la Diversidad', '4'),
    ('Administración de Recursos Financieros', '6'),
    ('Dirección Estratégica', '6'),
    ('Gestión del Talento Humano', '5'),
    ('Comercio Internacional', '5'),
    ('Administración de la Producción', '5'),
    ('Análisis Financiero', '5'),
    ('Gestión de la Tecnología de la Información', '6'),
    ('Gestión de la Innovación y el Cambio', '6'),
    ('Administración Pública', '5'),
    ('Gestión Ambiental', '4'),
    ('Mercadotecnia Digital', '5'),
    ('Emprendimiento Social', '5'),
    ('Gestión de Riesgos y Continuidad del Negocio', '5'),
    ('Estrategias de Negocios Internacionales', '6'),
	 ('Introducción al Diseño', '6'),
    ('Teoría del Diseño', '4'),
    ('Historia del Arte', '4'),
    ('Dibujo y Composición', '5'),
    ('Color y Teoría del Color', '6'),
    ('Fotografía y Retoque Digital', '5'),
    ('Tipografía y Composición de Textos', '4'),
    ('Diseño Gráfico I', '6'),
    ('Diseño Gráfico II', '6'),
    ('Diseño de Identidad Corporativa', '5'),
    ('Diseño Editorial', '6'),
    ('Ilustración y Visualización', '5'),
    ('Animación Digital', '5'),
    ('Diseño Web I', '6'),
    ('Diseño Web II', '6'),
    ('Diseño de Interfaz de Usuario', '5'),
    ('Diseño de Experiencia de Usuario (UX)', '5'),
    ('Diseño de Producto I', '6'),
    ('Diseño de Producto II', '6'),
    ('Diseño Industrial', '5'),
    ('Diseño Textil', '5'),
    ('Diseño de Moda', '4'),
    ('Diseño de Espacios Interiores', '5'),
    ('Diseño de Espacios Exteriores', '5'),
    ('Diseño de Espacios Comerciales', '4'),
    ('Diseño de Iluminación', '4'),
    ('Diseño Sostenible', '5'),
    ('Diseño Centrado en el Usuario', '6'),
    ('Diseño y Comunicación Visual', '5'),
    ('Diseño de Packaging', '5'),
    ('Diseño de Exposiciones', '4'),
    ('Diseño de Servicios', '6'),
    ('Diseño de Juegos y Entretenimiento', '6'),
    ('Realidad Virtual y Aumentada', '5'),
    ('Diseño y Creatividad', '4'),
    ('Gestión del Diseño', '5'),
    ('Proyecto de Diseño I', '6'),
    ('Proyecto de Diseño II', '6'),
    ('Diseño y Tecnología', '5'),
    ('Diseño Social y Comunitario', '5'),
	('Anatomía y Fisiología Animal I', '6'),
    ('Anatomía y Fisiología Animal II', '6'),
    ('Histología Veterinaria', '4'),
    ('Embriología Veterinaria', '4'),
    ('Genética y Mejoramiento Animal', '5'),
    ('Microbiología Veterinaria', '5'),
    ('Parasitología Veterinaria', '5'),
    ('Bioquímica Veterinaria', '6'),
    ('Farmacología Veterinaria', '6'),
    ('Inmunología Veterinaria', '5'),
    ('Patología Veterinaria I', '6'),
    ('Patología Veterinaria II', '6'),
    ('Nutrición y Alimentación Animal', '5'),
    ('Reproducción Animal', '5'),
    ('Medicina Veterinaria Preventiva', '5'),
    ('Epidemiología Veterinaria', '5'),
    ('Medicina Interna de Pequeños Animales', '6'),
    ('Medicina Interna de Grandes Animales', '6'),
    ('Cirugía Veterinaria I', '6'),
    ('Cirugía Veterinaria II', '6'),
    ('Radiología Veterinaria', '5'),
    ('Ultrasonografía Veterinaria', '5'),
    ('Oftalmología Veterinaria', '5'),
    ('Dermatología Veterinaria', '5'),
    ('Ortopedia y Traumatología Veterinaria', '6'),
    ('Cardiología Veterinaria', '5'),
    ('Neurología Veterinaria', '5'),
    ('Oncología Veterinaria', '5'),
    ('Etología y Bienestar Animal', '5'),
    ('Zootecnia y Producción Animal', '6'),
    ('Cirugía de Animales Exóticos', '5'),
    ('Medicina de Fauna Silvestre', '5'),
    ('Medicina de Animales de Laboratorio', '5'),
    ('Medicina de Animales de Zoológico', '5'),
    ('Medicina de Equinos', '5'),
    ('Medicina de Pequeños Mamíferos', '5'),
    ('Medicina de Aves y Reptiles', '5'),
    ('Medicina de Animales Acuáticos', '5'),
    ('Medicina de Animales de Producción', '6'),
    ('Teriogenología Veterinaria', '6'),
	 ('Introducción a la Gastronomía', '6'),
    ('Técnicas Culinarias I', '5'),
    ('Técnicas Culinarias II', '5'),
    ('Panadería y Repostería', '6'),
    ('Gastronomía Internacional', '6'),
    ('Enología y Maridaje', '5'),
    ('Gastronomía Molecular', '5'),
    ('Gestión de Restaurantes', '6'),
    ('Administración Culinaria', '6'),
    ('Diseño de Menús', '5');