INSERT INTO soldados (nombre, apellido, grado)
VALUES
    ('Juan', 'Pérez', 'Sargento Supervisor'),
    ('María', 'González', 'Aerotécnico Supervisor'),
    ('Carlos', 'Rodríguez', 'Guardia Nacional Sargento Ayudante'),
    ('Ana', 'Martínez', 'Sargento Ayudante'),
    ('Luis', 'López', 'Aerotécnico Ayudante'),
    ('Laura', 'Ramírez', 'Guardia Nacional Sargento Primero'),
    ('Alejandro', 'Gómez', 'Sargento Mayor de Primera'),
    ('Carolina', 'Díaz', 'Aerotécnico Mayor'),
    ('Manuel', 'Vargas', 'Guardia Nacional Sargento Segundo'),
    ('Patricia', 'Castro', 'Sargento Mayor de Segunda'),
    ('Ricardo', 'Méndez', 'Aerotécnico de Primera'),
    ('Diana', 'Herrera', 'Guardia Nacional Cabo Primero'),
    ('Gabriel', 'Silva', 'Sargento Mayor de Tercera'),
    ('Adriana', 'Navarro', 'Aerotécnico de Segunda'),
    ('Oscar', 'Ríos', 'Guardia Nacional Cabo Segundo'),
    ('Valentina', 'Ortega', 'Sargento Primero'),
    ('Hugo', 'Cortés', 'Aerotécnico de Tercera'),
    ('Fernanda', 'Fernández', 'Guardia Nacional Distinguido'),
    ('Martín', 'Mendoza', 'Sargento Segundo'),
    ('Sofía', 'Morales', 'Aerotécnico'),
    ('Eduardo', 'Camacho', 'Guardia Nacional Raso'),
    ('Diana', 'Gómez', 'Cabo Primero'),
    ('Javier', 'Torres', 'Cabo Segundo'),
    ('Verónica', 'Sánchez', 'Distinguido'),
    ('Miguel', 'Lara', 'Marinero Distinguido e Infante Distinguido'),
    ('Carla', 'Martínez', 'Soldado'),
    ('Fernando', 'González', 'Marinero e Infante de Marina'),
    ('Julieta', 'Romero', 'Alférez Mayor'),
    ('Héctor', 'Rojas', 'Guardiamarina Mayor'),
    ('Valeria', 'Cabrera', 'Alférez Auxiliar'),
    ('Alberto', 'Ortega', 'Guardiamarina Auxiliar'),
    ('Carmen', 'Paredes', 'Alférez'),
    ('Rafael', 'Méndez', 'Guardiamarina'),
    ('Cecilia', 'Delgado', 'Brigadier Mayor'),
    ('Leonardo', 'Vargas', 'Primer Brigadier'),
    ('Lorena', 'Cordero', 'Brigadier'),
    ('Eduardo', 'Silva', 'Sub-Brigadier'),
    ('Mariana', 'Fuentes', 'Distinguido'),
    ('Diego', 'Muñoz', 'Cadete'),
    ('Isabel', 'Pacheco', 'Maestro Técnico Supervisor'),
    ('José', 'Escobar', 'Maestre Supervisor'),
    ('Natalia', 'Guerrero', 'Maestro Técnico'),
    ('Antonio', 'Miranda', 'Maestre Mayor'),
    ('Cristina', 'Medina', 'Maestro Técnico de Primera'),
    ('Santiago', 'Soto', 'Maestre Principal'),
    ('Paulina', 'Castillo', 'Maestro Técnico de Segunda'),
    ('Eduardo', 'Cruz', 'Maestre Auxiliar'),
    ('Gabriela', 'Valenzuela', 'Maestro Técnico de Tercera'),
    ('Joaquín', 'Navarro', 'Maestre Técnico'),
    ('Valentina', 'Muñoz', 'Sargento Técnico de Primera'),
    ('Andrés', 'Fuentes', 'Maestre de Primera'),
    ('Bianca', 'Hernández', 'Sargento Técnico de Segunda'),
    ('Matías', 'Ortiz', 'Maestre de Segunda'),
    ('Daniela', 'Castillo', 'Sargento Técnico de Tercera'),
    ('Gustavo', 'Suárez', 'Maestre de Tercera'),
    ('María', 'Morales', 'General en Jefe'),
    ('Juan', 'Gutiérrez', 'Almirante'),
    ('Camila', 'Fernández', 'General de División'),
    ('José', 'Torres', 'Vicealmirante'),
    ('Samantha', 'Cabrera', 'General de Brigada'),
    ('Felipe', 'Salazar', 'Contralmirante'),
    ('Carolina', 'Sánchez', 'Coronel'),
    ('Alejandro', 'Castro', 'Capitán de Navío'),
    ('Laura', 'Gómez', 'Teniente Coronel'),
    ('David', 'Hernández', 'Capitán de Fragata'),
    ('Gabriela', 'Martínez', 'Mayor'),
    ('Sebastián', 'Ramírez', 'Capitán'),
    ('Isabella', 'Vargas', 'Teniente de Navío'),
    ('Daniel', 'Delgado', 'Teniente'),
    ('Camilo', 'Mendoza', 'Teniente de Fragata'),
    ('Valeria', 'Escobar', 'Sub-Teniente'),
    ('Mauricio', 'Cabrera', 'Alférez de Navío'),
    ('Victoria', 'Rojas', 'Capitán de Corbeta');
    ('Fernando', 'García', 'Sargento Supervisor'),
    ('Isabel', 'Hernández', 'Aerotécnico Supervisor'),
    ('Roberto', 'Gómez', 'Guardia Nacional Sargento Ayudante'),
    ('Mónica', 'Torres', 'Sargento Ayudante'),
    ('Jorge', 'Díaz', 'Aerotécnico Ayudante'),
    ('Marisol', 'Silva', 'Guardia Nacional Sargento Primero'),
    ('Miguel', 'Ortega', 'Sargento Mayor de Primera'),
    ('Liliana', 'Vargas', 'Aerotécnico Mayor'),
    ('Francisco', 'Rojas', 'Guardia Nacional Sargento Segundo'),
    ('Patricio', 'Navarro', 'Sargento Mayor de Segunda'),
    ('Alicia', 'Castro', 'Aerotécnico de Primera'),
    ('Christian', 'Fuentes', 'Guardia Nacional Cabo Primero'),
    ('Sandra', 'Méndez', 'Sargento Mayor de Tercera'),
    ('Víctor', 'Cordero', 'Aerotécnico de Segunda'),
    ('Elena', 'López', 'Guardia Nacional Cabo Segundo'),
    ('Rosa', 'Guzmán', 'Sargento Primero'),
    ('Adolfo', 'Romero', 'Aerotécnico de Tercera'),
    ('Ximena', 'Martínez', 'Guardia Nacional Distinguido'),
    ('Federico', 'Fernández', 'Sargento Segundo'),
    ('Nora', 'Castillo', 'Aerotécnico'),
    ('Gabriel', 'Gutiérrez', 'Guardia Nacional Raso'),
    ('Brenda', 'Paredes', 'Cabo Primero'),
    ('Ramón', 'Ortiz', 'Cabo Segundo'),
    ('Victoria', 'Suárez', 'Distinguido'),
    ('Héctor', 'Morales', 'Marinero Distinguido e Infante Distinguido'),
    ('Claudia', 'Soto', 'Soldado'),
    ('Camilo', 'Cruz', 'Marinero e Infante de Marina'),
    ('Aurora', 'Herrera', 'Alférez Mayor'),
    ('Benjamín', 'Salazar', 'Guardiamarina Mayor');